// src/components/portfolio-detail/components/carousel/carousel.svelte
<script lang="ts">
  import clsx from 'clsx';
  import type {
    MouseEventHandler,
    UIEventHandler,
  } from 'svelte/elements';

  import Arrow from '@/shared/icons/arrow.svelte';
  import type { SimpleMediaItem } from '@/shared/types/general';

  import CarouselItem from './carousel-item.svelte';

  export let mediaList: SimpleMediaItem[] = [];

  const totalMedia = mediaList.length;
  const indicatorIndices = Array.from(
    { length: totalMedia },
    (_, index) => index,
  );

  let scrollerElement: HTMLDivElement;
  let activeIndex = 0;
  let isFirstIndex = true;
  let isLastIndex = false;
  let translateXIndicator = 0;

  function getTranslateXIndicator(
    currentActiveIndex: number,
  ): number {
    const startThreshold = 2;

    if (currentActiveIndex < startThreshold) return 0;

    const endThreshold = totalMedia - 4;
    if (currentActiveIndex > endThreshold) {
      const endCenteringIndex = totalMedia - 5;
      return endCenteringIndex * 10;
    }

    const startCenteringIndex = currentActiveIndex - startThreshold;
    return startCenteringIndex * 10;
  }

  function updateIndex(index: number) {
    let newIndex = index;
    if (index < 0) newIndex = 0;
    else if (index >= totalMedia) newIndex = totalMedia - 1;

    scrollerElement.scrollTo({
      left: scrollerElement.clientWidth * newIndex,
      top: 0,
      behavior: 'smooth',
    });
  }

  const handlePrevClick: MouseEventHandler<HTMLButtonElement> = e => {
    e.stopPropagation();
    updateIndex(activeIndex - 1);
  };

  const handleNextClick: MouseEventHandler<HTMLButtonElement> = e => {
    e.stopPropagation();
    updateIndex(activeIndex + 1);
  };

  const handleScroll: UIEventHandler<HTMLDivElement> = e => {
    const scroller = e.currentTarget;
    const nextIndex = Math.round(
      scroller.scrollLeft / scroller.clientWidth,
    );
    if (nextIndex !== activeIndex) {
      activeIndex = nextIndex;
    }
  };

  $: {
    isFirstIndex = activeIndex === 0;
    isLastIndex = activeIndex === totalMedia - 1;
    translateXIndicator = getTranslateXIndicator(activeIndex);
  }
</script>

<div class="carousel">
  <div
    bind:this={scrollerElement}
    on:scroll={handleScroll}
    class="scrollbar-none relative w-full overflow-x-scroll scroll-snap-x"
  >
    <div class="flex transition-transform">
      {#each mediaList as media, index (media.url)}
        <CarouselItem
          {media}
          {scrollerElement}
          class="absolute top-0 left-0 w-full h-full"
          isActive={activeIndex === index}
          shouldEagerImageLoading={index === 0}
        />
      {/each}
    </div>
  </div>

  {#if mediaList.length > 1}
    <div
      class={clsx(
        'my-4 mx-auto max-w-[56px] overflow-x-hidden',
        'flex transition-all gap-1',
      )}
      style:transform={`translate3D(${translateXIndicator}, 0, 0)`}
    >
      {#each indicatorIndices as index}
        <span
          aria-current={index === activeIndex ? 'step' : 'false'}
          class="carousel__indicator-item"
        />
      {/each}
    </div>

    <button
      aria-hidden={isFirstIndex}
      class="carousel__arrow carousel__arrow_prev"
      disabled={isFirstIndex}
      on:click={handlePrevClick}
    >
      <Arrow />
      <span class="visually-hidden">Previous</span>
    </button>

    <button
      aria-hidden={isLastIndex}
      class="carousel__arrow carousel__arrow_next"
      disabled={isLastIndex}
      on:click={handleNextClick}
    >
      <Arrow />
      <span class="visually-hidden">Next</span>
    </button>
  {/if}
</div>

<style>
  .carousel {
    @apply relative w-full bg-neutral-bright;
  }

  :global(.dark) .carousel {
    @apply bg-neutral-dim;
  }

  .carousel__indicator-item {
    @apply flex-grow-0 flex-shrink-0 flex-basis-auto;
    @apply w-2 h-2 bg-neutral-bright2 rounded-full;
  }

  .carousel__indicator-item[aria-current='step'] {
    @apply bg-neutral-dim;
  }

  :global(.dark) .carousel__indicator-item {
    @apply bg-neutral-dim2;
  }

  :global(.dark) .carousel__indicator-item[aria-current='step'] {
    @apply bg-neutral-bright;
  }

  .carousel__arrow {
    @apply absolute top-1/2 items-center justify-center w-7 h-7;
    @apply bg-neutral-bright0 text-neutral-dim;
    @apply rounded-full cursor-pointer border-none outline-none;
    @apply opacity-0 transition-opacity visible;
  }

  :global(.dark) .carousel__arrow {
    @apply bg-neutral-dim0 text-neutral-bright;
  }

  :global(.desktop) .carousel__arrow {
    display: flex;
  }

  :global(.mobile) .carousel__arrow {
    display: none;
  }

  .carousel:hover > .carousel__arrow {
    @apply shadow-lg opacity-100;
  }

  .carousel__arrow[aria-hidden='true'] {
    visibility: hidden;
  }

  .carousel__arrow_next {
    right: 10px;
    transform: rotate(180deg) translate(0, 50%);
  }

  .carousel__arrow_prev {
    left: 10px;
    transform: translate(0, -50%);
  }
</style>

// app/components/carousel.tsx
import type { MouseEvent, UIEvent } from 'react';
import { useMemo, useCallback, useRef, useState } from 'react';

import clsx from 'clsx';

import ArrowIcon from '~/icons/arrow';
import type { SimpleMediaItem } from '~/types/general';

import VisuallyHidden from './visually-hidden';

interface CarouselItemProps extends SimpleMediaItem {
  isActive: boolean;
  className: string;
}

function CarouselItem({
  alt,
  className,
  height,
  isActive,
  mime,
  resourceType,
  url,
  width,
}: CarouselItemProps) {
  return (
    <div
      aria-current={isActive}
      className='scroll-snap-start flex-grow flex-shrink-0 flex-basis items-center justify-center'
    >
      <div className='relative w-full pb-[100%]'>
        {resourceType === 'image' && (
          <img
            alt={alt}
            className={className}
            height={height}
            src={url}
            title={alt}
            width={width}
          />
        )}
        {resourceType === 'video' &&
          (mime === 'video/webm' || mime === 'video/mp4') && (
            <video
              className={className}
              controls
              height={height}
              title={alt}
              width={width}
            >
              <source src={url} type={mime} />
              Sorry, your browser doesn't support embedded videos.
            </video>
          )}
      </div>
    </div>
  );
}

interface CarouselProps {
  mediaList: SimpleMediaItem[];
}

export default function Carousel({ mediaList }: CarouselProps) {
  const totalMedia = mediaList.length;
  const isMultiple = totalMedia > 1;

  const scrollerRef = useRef<HTMLDivElement>(null);
  const [activeIndex, setActiveIndex] = useState(0);
  const isFirstIndex = activeIndex === 0;
  const isLastIndex = activeIndex === totalMedia - 1;

  const translateXIndicator = useMemo(() => {
    const startThreshold = 2;

    if (activeIndex >= startThreshold) {
      const endThreshold = totalMedia - 4;
      if (activeIndex > endThreshold) {
        const endCenteringIndex = totalMedia - 5;
        return endCenteringIndex * 10;
      }

      const startCenteringIndex = activeIndex - startThreshold;
      return startCenteringIndex * 10;
    }

    return 0;
  }, [activeIndex, totalMedia]);

  const handleScroll = useCallback(
    (e: UIEvent<HTMLDivElement>) => {
      const scroller = e.currentTarget;
      const nextIndex = Math.round(
        scroller.scrollLeft / scroller.clientWidth,
      );
      if (nextIndex !== activeIndex) setActiveIndex(nextIndex);
    },
    [activeIndex],
  );

  const updateIndex = useCallback(
    (index: number) => {
      if (!totalMedia) return;

      let newIndex = index;
      if (index < 0) newIndex = 0;
      else if (index >= totalMedia) newIndex = totalMedia - 1;

      const scroller = scrollerRef.current;
      scroller?.scrollTo({
        left: scroller?.clientWidth * newIndex,
        top: 0,
        behavior: 'smooth',
      });
    },
    [totalMedia],
  );

  const handleClickNext = useCallback(
    (e: MouseEvent) => {
      e.stopPropagation();
      updateIndex(activeIndex + 1);
    },
    [activeIndex, updateIndex],
  );

  const handleClickPrev = useCallback(
    (e: MouseEvent) => {
      e.stopPropagation();
      updateIndex(activeIndex - 1);
    },
    [activeIndex, updateIndex],
  );

  return (
    <div className='carousel'>
      <div
        className='scrollbar-none relative w-full overflow-x-scroll scroll-snap-x'
        onScroll={handleScroll}
        ref={scrollerRef}
      >
        <div className='flex transition-transform'>
          {mediaList.map((mediaItem, index) => (
            <CarouselItem
              key={`${mediaItem.url}-${index}`}
              className='absolute top-0 left-0 w-full h-full'
              isActive={activeIndex === index}
              {...mediaItem}
            />
          ))}
        </div>
      </div>

      {isMultiple && (
        <div
          className={clsx(
            'my-4 mx-auto max-w-[56px] overflow-x-hidden',
            'flex transition-all gap-1',
          )}
          style={{ transform: `translateX(${translateXIndicator})` }}
        >
          {Array.from({ length: totalMedia }, (_, index) => (
            <span
              aria-current={index === activeIndex ? 'step' : 'false'}
              key={`carousel-indicator-${index}`}
              className='carousel__indicator-item'
            />
          ))}
        </div>
      )}

      {isMultiple && (
        <>
          <button
            aria-hidden={isFirstIndex}
            className='carousel__arrow carousel__arrow_prev'
            onClick={handleClickPrev}
          >
            <ArrowIcon />
            <VisuallyHidden>Previous</VisuallyHidden>
          </button>
          <button
            aria-hidden={isLastIndex}
            className='carousel__arrow carousel__arrow_next'
            onClick={handleClickNext}
          >
            <ArrowIcon />
            <VisuallyHidden>Next</VisuallyHidden>
          </button>
        </>
      )}
    </div>
  );
}
