// src/components/stories/layout/components/invisible-nav-buttons.svelte
<script lang="ts">
  import {
    activeStory,
    storiesAction,
  } from '@/shared/stores/stories';

  $: ({ canNext, canPrev } = $activeStory);
</script>

<button
  class="btn btn-text invisible-nav-btn invisible-nav-btn_prev"
  disabled={!canPrev}
  title="Prev"
  on:click={$storiesAction.prev}
>
  <span class="visually-hidden">Prev</span>
</button>

<button
  class="btn btn-text invisible-nav-btn invisible-nav-btn_next"
  disabled={!canNext}
  title="Next"
  on:click={$storiesAction.next}
>
  <span class="visually-hidden">Next</span>
</button>

<style>
  .invisible-nav-btn {
    position: absolute;
    top: 0;
    width: calc(100% / 3);
    height: 100%;
  }

  .invisible-nav-btn_prev {
    left: 0;
  }

  .invisible-nav-btn_next {
    right: 0;
  }
</style>

// app/layouts/stories-layout/components/invisible-nav-buttons.tsx
import { useCallback } from 'react';

import VisuallyHidden from '~/components/visually-hidden';
import {
  trackNextHighlightClick,
  trackNextStoryClick,
  trackPrevHighlightClick,
  trackPrevStoryClick,
} from '~/lib/analytics';
import {
  useActiveStory,
  goToPrevStory,
  goToNextStory,
} from '~/store/stories';

import type { StoriesLayoutProps } from '../types';

export default function InvisibleNavButtons({
  name,
}: Pick<StoriesLayoutProps, 'name'>) {
  const {
    activeIndex,
    activeStory: { title },
    canNext,
    canPrev,
  } = useActiveStory();

  const handlePrev = useCallback(() => {
    goToPrevStory();

    if (name === 'stories') {
      trackPrevStoryClick({
        storyIndex: activeIndex,
        storyTitle: title,
      });
      return;
    }

    trackPrevHighlightClick({
      highlightIndex: activeIndex,
      highlightName: name,
      highlightTitle: title,
    });
  }, [activeIndex, name, title]);

  const handleNext = useCallback(() => {
    goToNextStory();

    if (name === 'stories') {
      trackNextStoryClick({
        storyIndex: activeIndex,
        storyTitle: title,
      });
      return;
    }

    trackNextHighlightClick({
      highlightIndex: activeIndex,
      highlightName: name,
      highlightTitle: title,
    });
  }, [activeIndex, name, title]);

  return (
    <>
      <button
        disabled={!canPrev}
        onClick={handlePrev}
        className='btn btn-text w-1/3 h-full absolute top-0 left-0'
        title='Prev'
      >
        <VisuallyHidden>Previous story</VisuallyHidden>
      </button>
      <button
        disabled={!canNext}
        onClick={handleNext}
        className='btn btn-text w-1/3 h-full absolute top-0 right-0'
        title='Next'
      >
        <VisuallyHidden>Next story</VisuallyHidden>
      </button>
    </>
  );
}
