// src/components/stories/layout/components/audio-toggle-button.svelte
<script lang="ts">
  import SoundOff from '@/shared/icons/sound-off.svelte';
  import SoundOn from '@/shared/icons/sound-on.svelte';
  import {
    isStoryMuted,
    storiesAction,
  } from '@/shared/stores/stories';

  function handleClick() {
    $storiesAction.toggleAudio();
  }
</script>

<button
  class="btn btn-text text-inherit"
  title="Toggle audio"
  on:click={handleClick}
>
  {#if $isStoryMuted}
    <SoundOff ariaLabel="Audio is muted" size={16} />
  {:else}
    <SoundOn ariaLabel="Audio is playing" size={16} />
  {/if}
  <span class="visually-hidden">Toggle audio</span>
</button>

// app/pages/stories/components/audio-toggle-button.tsx
import VisuallyHidden from '~/components/visually-hidden';
import SoundOffIcon from '~/icons/sound-off';
import SoundOnIcon from '~/icons/sound-on';
import { useStoryIsMuted, toggleStoryAudio } from '~/store/stories';

export default function AudioToggleButton() {
  const isMuted = useStoryIsMuted();

  return (
    <button
      className='btn btn-text text-inherit'
      onClick={toggleStoryAudio}
      title='Toggle audio'
    >
      {isMuted ? (
        <SoundOffIcon
          aria-label='Audio is muted'
          width={16}
          height={16}
        />
      ) : (
        <SoundOnIcon
          aria-label='Audio is playing'
          width={16}
          height={16}
        />
      )}
      <VisuallyHidden>Toggle audio</VisuallyHidden>
    </button>
  );
}
