// src/components/stories/layout/components/invisible-nav-buttons.svelte
<script lang="ts">
  import {
    activeStory,
    storiesAction,
  } from '@/shared/stores/stories';

  $: ({ canNext, canPrev } = $activeStory);
</script>

<button
  class="btn btn-text invisible-nav-btn invisible-nav-btn_prev"
  disabled={!canPrev}
  title="Prev"
  on:click={$storiesAction.prev}
>
  <span class="visually-hidden">Prev</span>
</button>

<button
  class="btn btn-text invisible-nav-btn invisible-nav-btn_next"
  disabled={!canNext}
  title="Next"
  on:click={$storiesAction.next}
>
  <span class="visually-hidden">Next</span>
</button>

<style>
  .invisible-nav-btn {
    position: absolute;
    top: 0;
    width: calc(100% / 3);
    height: 100%;
  }

  .invisible-nav-btn_prev {
    left: 0;
  }

  .invisible-nav-btn_next {
    right: 0;
  }
</style>

// app/pages/stories/components/invisible-nav-buttons.tsx
import VisuallyHidden from '~/components/visually-hidden';
import {
  useActiveStory,
  goToPrevStory,
  goToNextStory,
} from '~/store/stories';

export default function InvisibleNavButtonss() {
  const { canNext, canPrev } = useActiveStory();

  return (
    <>
      <button
        disabled={!canPrev}
        onClick={goToPrevStory}
        className='btn btn-text w-1/3 h-full absolute top-0 left-0'
        title='Prev'
      >
        <VisuallyHidden>Previous story</VisuallyHidden>
      </button>
      <button
        disabled={!canNext}
        onClick={goToNextStory}
        className='btn btn-text w-1/3 h-full absolute top-0 right-0'
        title='Next'
      >
        <VisuallyHidden>Next story</VisuallyHidden>
      </button>
    </>
  );
}
