// src/components/stories/layout/components/progress.svelte
<script lang="ts">
  import { storyProgress } from '@/shared/stores/stories';

  export let slug: string;

  $: progress = $storyProgress[slug];
</script>

<div class="progress" style:width={Math.min(progress, 100) + '%'} />

<style>
  .progress {
    position: absolute;
    top: 0;
    background-color: var(--color-neutral-bright);
    transition-property: width;
    transition-timing-function: linear;
    transition-duration: 10ms;
    will-change: width;
  }
</style>

// app/pages/stories/components/progress.tsx
import { useStoryProgress } from '~/store/stories';

interface ProgressProps {
  slug: string;
}

export default function Progress({ slug }: ProgressProps) {
  const progress = useStoryProgress(slug);

  return (
    <div
      className='absolute top-0 transition-[width] will-change-[width] bg-neutral-bright'
      style={{
        width: `${Math.min(progress, 100)}%`,
        transitionTimingFunction: 'linear',
        transitionDuration: '10ms',
      }}
    />
  );
}
